# Generated by Django 5.1.7 on 2025-03-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_image_product_main_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
